import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import ClientNavbar from "@/components/ClientNavbar"; // client wrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read token on client side
  const token =
    typeof window !== "undefined" ? localStorage.getItem("token") : null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <CartProvider>
          {/* Key forces Navbar to remount on login/logout */}
          <ClientNavbar key={token || "guest"} />
          <main>{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
